name: ci

on:
  push:
    branches:
      - 'dev'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_LABEL: ${{ steps.convert-repository-name.outputs.DOCKER_LABEL }}
    steps:
      -
        name: "Convert repository name to docker hub repository name"
        id: convert-repository-name
        run: |
          echo "::set-output name=DOCKER_LABEL::$(sed 's/^[[:upper:]]/\L&/;s/[[:upper:]]/\L_&/g' <<< '${{ github.event.repository.name }}')"
      -
        name: "Check if docker repository exists"
        run: |
          curl --location --fail --header "Authorization: JWT $(curl --location --header "Content-type: application/json" --request POST --data '{"username": "${{ secrets.DOCKERHUB_USERNAME }}", "password": "${{ secrets.DOCKERHUB_TOKEN }}"}' https://hub.docker.com/v2/users/login | jq -r '.token')" https://hub.docker.com/v2/repositories/gisat/${{ steps.convert-repository-name.outputs.DOCKER_LABEL }}
  
  test:
    runs-on: ubuntu-latest
    needs: [check]
    services:
        postgres:
            image: postgis/postgis
            ports:
                - '5432:5432'
            env:
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: panther
    steps:
        - 
          name: "Checkout"
          uses: actions/checkout@v3.1.0
        - 
          name: "Setup NodeJS environment"
          uses: actions/setup-node@v3.5.1
          with:
              node-version: '14.x'
        - 
          name: "Install dependencies"
          run: |
            npm ci
        - 
          name: "Start application"
          run: |
            npm run start &
        - 
          name: "Run application tests"
          run: |
            npm run test:wait
  
  build:
    runs-on: ubuntu-latest
    needs: [check, test]
    steps:
      - 
        name: "Checkout"
        uses: actions/checkout@v3.1.0
      - 
        name: "Get docker image metadata"
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gisat/${{ needs.check.outputs.DOCKER_LABEL }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
          flavor: |
            latest=false
      - 
        name: "Login to DockerHub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: "Build and push"
        uses: docker/build-push-action@v4
        if: ${{ success() }}
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: [check, test, build]
    steps:
      -
        name: "Deploy application on remote server"
        run: |
          curl --location --fail "https://ptr.gisat.cz/webhook/hooks/deploy?token=102aeeb9-233d-4e29-97c4-91cdc8852d97&service=be"
  